USE [master]
GO

/****** Object:  Database [EmployeeApp]    Script Date: 10/02/2020 23:28:42 ******/
CREATE DATABASE [EmployeeApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EmployeeApp', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\EmployeeApp.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'EmployeeApp_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\EmployeeApp_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EmployeeApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EmployeeApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EmployeeApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EmployeeApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EmployeeApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EmployeeApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [EmployeeApp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EmployeeApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EmployeeApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EmployeeApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EmployeeApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EmployeeApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EmployeeApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EmployeeApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EmployeeApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EmployeeApp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EmployeeApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EmployeeApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EmployeeApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EmployeeApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EmployeeApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EmployeeApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EmployeeApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EmployeeApp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EmployeeApp] SET  MULTI_USER 
GO

ALTER DATABASE [EmployeeApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EmployeeApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EmployeeApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EmployeeApp] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [EmployeeApp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EmployeeApp] SET  READ_WRITE 
GO

